#ifndef PIXELSIM_CONFIG_H
#define PIXELSIM_CONFIG_H

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#define GRAVITY 1.1
#define FRICTION 0.5
#define BOUNCE_DAMP 0.5
#define PLAYER_SPEED 1
#define PLAYER_JUMP_STRENGTH 20

#define PLAYER_START_X 50
#define PLAYER_START_Y 50
#define PLAYER_START_W 20
#define PLAYER_START_H 20
#define PLAYER_START_VEL_X 0
#define PLAYER_START_VEL_Y 0
#define PLAYER_START_COLOR {255, 255, 255}


#endif //PIXELSIM_CONFIG_H